management_server:
  livez:
    enabled: true
    path: "/livez"
  readyz:
    enabled: true
    path: "/readyz"
  disable_plugin_api: false
  disable_health_api: false
  disable_console: false
  cors: https://localhost:8000

mcp_server:
  cors: https://localhost:8000
plugins:
- name: time
  path: plugins/target/wasm32-wasip1/debug/time_plugin.wasm
  manifest:
    timeout_ms: 2000
    memory:
      max_pages: 32
- name: hash
  url: plugins/target/wasm32-wasip1/debug/hash_plugin.wasm

tls:
  key: assets/dev_server.key
  cert: assets/dev_server.pem

