accepted = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "CC0-1.0",
    "Unlicense",
    "OpenSSL",
    "Python-2.0",
    "MIT-0",
    "PostgreSQL",
    "NCSA",
    "X11",
    "Artistic-2.0",
    "Unicode-3.0",
    "MPL-2.0",
    "CDLA-Permissive-2.0"
]
ignore-build-dependencies = true
ignore-dev-dependencies = true




